import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parse } from "yaml";
import { format, resolveConfig } from "prettier";

import { articleFrontmatterSchema, type ArticleFrontmatter } from "../src/content/schema";
import { authors } from "../src/data/authors";
import { categories } from "../src/data/categories";

const SCRIPT_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const ARTICLE_DIRECTORY = resolve(SCRIPT_DIRECTORY, "../content/articles");
const TEMPLATE_DIRECTORY = resolve(SCRIPT_DIRECTORY, "../content/templates");
const GENERATED_DIRECTORY = resolve(SCRIPT_DIRECTORY, "../src/content/generated");
const ALLOWED_COMPONENTS = new Set(["Callout", "Quote", "Figure", "KeyPoints"]);

export interface ParsedEditorialFile {
  frontmatter: ArticleFrontmatter;
  body: string;
  path: string;
}

/** Parse and validate one constrained MDX editorial file. */
export function parseEditorialFile(source: string, path = "conteúdo.mdx"): ParsedEditorialFile {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) throw new Error(`${path}: frontmatter delimitado por --- é obrigatório.`);

  let rawFrontmatter: unknown;
  try {
    rawFrontmatter = parse(match[1]);
  } catch (error) {
    throw new Error(`${path}: YAML inválido: ${String(error)}`);
  }

  const result = articleFrontmatterSchema.safeParse(rawFrontmatter);
  if (!result.success) {
    throw new Error(
      `${path}: frontmatter inválido:\n${result.error.issues
        .map((issue) => `- ${issue.path.join(".")}: ${issue.message}`)
        .join("\n")}`,
    );
  }

  validateSafeMdx(match[2], path);
  return { frontmatter: result.data, body: match[2], path };
}

/** Reject executable MDX constructs and components outside the editorial whitelist. */
export function validateSafeMdx(body: string, path: string): void {
  if (/^\s*(?:import|export)\s/m.test(body)) {
    throw new Error(`${path}: import/export não é permitido no conteúdo editorial.`);
  }
  if (/[{}]/.test(body)) {
    throw new Error(`${path}: expressões JavaScript em MDX não são permitidas.`);
  }

  for (const match of body.matchAll(/<\/?([A-Za-z][\w.]*)\b/g)) {
    const component = match[1];
    if (!ALLOWED_COMPONENTS.has(component)) {
      throw new Error(`${path}: componente MDX não autorizado: ${component}.`);
    }
  }
}

/** Validate cross-record invariants such as unique slugs and existing taxonomy. */
export function validateArticleCollection(records: ArticleFrontmatter[]): void {
  const slugs = new Set<string>();
  const categorySet = new Set(categories.map((category) => category.slug));

  for (const article of records) {
    if (slugs.has(article.slug)) throw new Error(`Slug duplicado: ${article.slug}.`);
    slugs.add(article.slug);
    if (!authors[article.author])
      throw new Error(`${article.slug}: autor inexistente: ${article.author}.`);
    if (!categorySet.has(article.category)) {
      throw new Error(`${article.slug}: categoria inexistente: ${article.category}.`);
    }
  }
}

async function loadArticles(): Promise<ParsedEditorialFile[]> {
  const names = (await readdir(ARTICLE_DIRECTORY)).filter((name) => name.endsWith(".mdx")).sort();
  const files = await Promise.all(
    names.map(async (name) => {
      const path = join(ARTICLE_DIRECTORY, name);
      const parsed = parseEditorialFile(
        await readFile(path, "utf8"),
        relative(process.cwd(), path),
      );
      if (basename(name, ".mdx") !== parsed.frontmatter.slug) {
        throw new Error(`${name}: o nome do arquivo deve ser igual ao slug.`);
      }
      return parsed;
    }),
  );
  validateArticleCollection(files.map((file) => file.frontmatter));
  return files;
}

function generatedIndex(files: ParsedEditorialFile[]): string {
  return `// Generated by scripts/generate-content.ts. Do not edit manually.\nimport type { ArticleFrontmatter } from "@/content/schema";\n\nexport const articleRecords = ${JSON.stringify(
    files.map((file) => file.frontmatter),
    null,
    2,
  )} as const satisfies readonly ArticleFrontmatter[];\n`;
}

function generatedLoaders(files: ParsedEditorialFile[]): string {
  const entries = files
    .map(
      ({ frontmatter }) =>
        `  ${JSON.stringify(frontmatter.slug)}: () => import(${JSON.stringify(`../../../content/articles/${frontmatter.slug}.mdx`)}),`,
    )
    .join("\n");
  return `// Generated by scripts/generate-content.ts. Do not edit manually.\nimport type { MdxModuleLoader } from "@/content/types";\n\nexport const articleLoaders: Record<string, MdxModuleLoader> = {\n${entries}\n};\n`;
}

async function emit(path: string, content: string, check: boolean): Promise<void> {
  let current = "";
  try {
    current = await readFile(path, "utf8");
  } catch {
    // A missing generated file is handled below.
  }
  if (current === content) return;
  if (check) throw new Error(`${relative(process.cwd(), path)} está desatualizado.`);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

async function main(): Promise<void> {
  const files = await loadArticles();
  const check = process.argv.includes("--check");
  const templates = (await readdir(TEMPLATE_DIRECTORY)).filter((name) => name.endsWith(".mdx"));
  const demos = files.filter((file) => file.frontmatter.isDemo);
  const warnings = files.flatMap((file) => {
    const result: string[] = [];
    if (file.frontmatter.isDemo)
      result.push(`${file.path}: conteúdo demonstrativo, nunca oficial.`);
    if (file.frontmatter.cover.license === "unknown") {
      result.push(`${file.path}: licença de capa desconhecida; bloqueio para conteúdo real.`);
    }
    if (file.frontmatter.sourceUrls.length > 0 && file.frontmatter.sources.length === 0) {
      result.push(
        `${file.path}: migre sourceUrls para fontes estruturadas antes da publicação real.`,
      );
    }
    return result;
  });
  const prettierConfig = (await resolveConfig(join(GENERATED_DIRECTORY, "articles.ts"))) ?? {};
  await emit(
    join(GENERATED_DIRECTORY, "articles.ts"),
    await format(generatedIndex(files), { ...prettierConfig, parser: "typescript" }),
    check,
  );
  await emit(
    join(GENERATED_DIRECTORY, "loaders.ts"),
    await format(generatedLoaders(files), { ...prettierConfig, parser: "typescript" }),
    check,
  );
  for (const warning of warnings) console.warn(`[warning] ${warning}`);
  console.log(
    `Validação editorial: ${files.length} artigos (${demos.length} demos), ${templates.length} templates excluídos do índice, ${warnings.length} warnings, 0 erros${check ? "" : "; índice atualizado"}.`,
  );
}

if (import.meta.main) await main();
