/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PoliticaEditorialRouteImport } from './routes/politica-editorial'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AutorSlugRouteImport } from './routes/autor.$slug'
import { Route as ArtigoSlugRouteImport } from './routes/artigo.$slug'
import { Route as AdminNewsroomRouteImport } from './routes/admin.newsroom'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminResearchWorkspaceScientificWorkIdRouteImport } from './routes/admin.research-workspace.$scientificWorkId'
import { Route as AdminNewsroomSectionRouteImport } from './routes/admin.newsroom_.$section'
import { Route as AdminNewsroomSectionIdRouteImport } from './routes/admin.newsroom_.$section.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaEditorialRoute = PoliticaEditorialRouteImport.update({
  id: '/politica-editorial',
  path: '/politica-editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorSlugRoute = AutorSlugRouteImport.update({
  id: '/autor/$slug',
  path: '/autor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigoSlugRoute = ArtigoSlugRouteImport.update({
  id: '/artigo/$slug',
  path: '/artigo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsroomRoute = AdminNewsroomRouteImport.update({
  id: '/admin/newsroom',
  path: '/admin/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResearchWorkspaceScientificWorkIdRoute =
  AdminResearchWorkspaceScientificWorkIdRouteImport.update({
    id: '/admin/research-workspace/$scientificWorkId',
    path: '/admin/research-workspace/$scientificWorkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminNewsroomSectionRoute = AdminNewsroomSectionRouteImport.update({
  id: '/admin/newsroom_/$section',
  path: '/admin/newsroom/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsroomSectionIdRoute = AdminNewsroomSectionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminNewsroomSectionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/newsletter': typeof NewsletterRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsroom': typeof AdminNewsroomRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/admin/newsroom/$section': typeof AdminNewsroomSectionRouteWithChildren
  '/admin/research-workspace/$scientificWorkId': typeof AdminResearchWorkspaceScientificWorkIdRoute
  '/admin/newsroom/$section/$id': typeof AdminNewsroomSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/newsletter': typeof NewsletterRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsroom': typeof AdminNewsroomRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/admin/newsroom/$section': typeof AdminNewsroomSectionRouteWithChildren
  '/admin/research-workspace/$scientificWorkId': typeof AdminResearchWorkspaceScientificWorkIdRoute
  '/admin/newsroom/$section/$id': typeof AdminNewsroomSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/metodologia': typeof MetodologiaRoute
  '/newsletter': typeof NewsletterRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsroom': typeof AdminNewsroomRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/admin/newsroom_/$section': typeof AdminNewsroomSectionRouteWithChildren
  '/admin/research-workspace/$scientificWorkId': typeof AdminResearchWorkspaceScientificWorkIdRoute
  '/admin/newsroom_/$section/$id': typeof AdminNewsroomSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/contato'
    | '/metodologia'
    | '/newsletter'
    | '/politica-editorial'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin/login'
    | '/admin/newsroom'
    | '/artigo/$slug'
    | '/autor/$slug'
    | '/categoria/$slug'
    | '/admin/newsroom/$section'
    | '/admin/research-workspace/$scientificWorkId'
    | '/admin/newsroom/$section/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/contato'
    | '/metodologia'
    | '/newsletter'
    | '/politica-editorial'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin/login'
    | '/admin/newsroom'
    | '/artigo/$slug'
    | '/autor/$slug'
    | '/categoria/$slug'
    | '/admin/newsroom/$section'
    | '/admin/research-workspace/$scientificWorkId'
    | '/admin/newsroom/$section/$id'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/contato'
    | '/metodologia'
    | '/newsletter'
    | '/politica-editorial'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin/login'
    | '/admin/newsroom'
    | '/artigo/$slug'
    | '/autor/$slug'
    | '/categoria/$slug'
    | '/admin/newsroom_/$section'
    | '/admin/research-workspace/$scientificWorkId'
    | '/admin/newsroom_/$section/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  ContatoRoute: typeof ContatoRoute
  MetodologiaRoute: typeof MetodologiaRoute
  NewsletterRoute: typeof NewsletterRoute
  PoliticaEditorialRoute: typeof PoliticaEditorialRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsroomRoute: typeof AdminNewsroomRoute
  ArtigoSlugRoute: typeof ArtigoSlugRoute
  AutorSlugRoute: typeof AutorSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  AdminNewsroomSectionRoute: typeof AdminNewsroomSectionRouteWithChildren
  AdminResearchWorkspaceScientificWorkIdRoute: typeof AdminResearchWorkspaceScientificWorkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-editorial': {
      id: '/politica-editorial'
      path: '/politica-editorial'
      fullPath: '/politica-editorial'
      preLoaderRoute: typeof PoliticaEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor/$slug': {
      id: '/autor/$slug'
      path: '/autor/$slug'
      fullPath: '/autor/$slug'
      preLoaderRoute: typeof AutorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigo/$slug': {
      id: '/artigo/$slug'
      path: '/artigo/$slug'
      fullPath: '/artigo/$slug'
      preLoaderRoute: typeof ArtigoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsroom': {
      id: '/admin/newsroom'
      path: '/admin/newsroom'
      fullPath: '/admin/newsroom'
      preLoaderRoute: typeof AdminNewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/research-workspace/$scientificWorkId': {
      id: '/admin/research-workspace/$scientificWorkId'
      path: '/admin/research-workspace/$scientificWorkId'
      fullPath: '/admin/research-workspace/$scientificWorkId'
      preLoaderRoute: typeof AdminResearchWorkspaceScientificWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsroom_/$section': {
      id: '/admin/newsroom_/$section'
      path: '/admin/newsroom/$section'
      fullPath: '/admin/newsroom/$section'
      preLoaderRoute: typeof AdminNewsroomSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsroom_/$section/$id': {
      id: '/admin/newsroom_/$section/$id'
      path: '/$id'
      fullPath: '/admin/newsroom/$section/$id'
      preLoaderRoute: typeof AdminNewsroomSectionIdRouteImport
      parentRoute: typeof AdminNewsroomSectionRoute
    }
  }
}

interface AdminNewsroomSectionRouteChildren {
  AdminNewsroomSectionIdRoute: typeof AdminNewsroomSectionIdRoute
}

const AdminNewsroomSectionRouteChildren: AdminNewsroomSectionRouteChildren = {
  AdminNewsroomSectionIdRoute: AdminNewsroomSectionIdRoute,
}

const AdminNewsroomSectionRouteWithChildren =
  AdminNewsroomSectionRoute._addFileChildren(AdminNewsroomSectionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  ContatoRoute: ContatoRoute,
  MetodologiaRoute: MetodologiaRoute,
  NewsletterRoute: NewsletterRoute,
  PoliticaEditorialRoute: PoliticaEditorialRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsroomRoute: AdminNewsroomRoute,
  ArtigoSlugRoute: ArtigoSlugRoute,
  AutorSlugRoute: AutorSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  AdminNewsroomSectionRoute: AdminNewsroomSectionRouteWithChildren,
  AdminResearchWorkspaceScientificWorkIdRoute:
    AdminResearchWorkspaceScientificWorkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
